CREATE TABLE WEATHER_MEASUREMENT(
   ID INTEGER PRIMARY KEY,
   AMBIENT_TEMPERATURE DECIMAL(6,2) NOT NULL,
   GROUND_TEMPERATURE DECIMAL(6,2) NOT NULL,
   AIR_QUALITY DECIMAL(6,2) NOT NULL,
   AIR_PRESSURE DECIMAL(6,2) NOT NULL,
   HUMIDITY DECIMAL(6,2) NOT NULL,
   WIND_DIRECTION DECIMAL(6,2) NULL,
   WIND_SPEED DECIMAL(6,2) NOT NULL,
   WIND_GUST_SPEED DECIMAL(6,2) NOT NULL,
   RAINFALL DECIMAL (6,2) NOT NULL,
   CREATED DATETIME DEFAULT current_timestamp
);
